export const V18_MEDIA_STATUS = Object.freeze({
  CANDIDATE: 'candidate',
  MISSING: 'missing',
  REJECTED: 'rejected',
  FRAGMENTED: 'fragmented',
  UNVERIFIED: 'unverified',
  ASSEMBLY_PENDING: 'assembly_pending',
})

// V18 的固定叙事顺序。素材存在不代表已经通过真实性与连续性验收。
export const V18_STORY = [
  {
    id: 'v18-01-vault',
    sequence: 1,
    eyebrow: '给高校学生使用的 AI 学习软件',
    title: 'AI 已经给出答案，学生却仍可能没有学会',
    uniquePoint: 'AXIOM 给高校学生使用，并且不把“答案出现”当成学习终点。',
    subtitle: 'AXIOM：学生亲自讲清 → 证据审核 → 改变下一步',
    narration: '通用 AI 会解释和生成，课程平台会组织内容，笔记工具会保存；但学生是否掌握，仍常靠自己判断。AXIOM Space 是给高校学生使用的 AI 学习软件：它让学生输出，用证据确认掌握，再让证据改变下一步。接下来，我们沿着小林的一次真实学习证明这件事。为完成 Java Web 课程项目，小林进入自己的课程仓库。',
    media: {
      mode: 'product-video+text-overlay',
      master: 'M01',
      status: V18_MEDIA_STATUS.CANDIDATE,
      candidates: ['assets/videos/scene-22-enter-vault.mp4'],
      missing: [],
      note: '01 只使用进入仓库实录；问题对照与机制均用文字叠加。',
    },
    beats: [
      { time: '0-3', visual: '仓库选择页', text: '产品主语＋主标题' },
      { time: '3-8', visual: '选择 Java Web 仓库并进入', text: '学生亲自讲清' },
      { time: '8-18', visual: '资料、画像、卡片和进度入口', text: '证据审核 → 改变下一步' },
      { time: '18-24', visual: '进入初始画像入口', text: '进入仓库 → 建立初始画像' },
    ],
    visual: {
      layout: 'vault-entry-proof',
      focus: 'java-web-vault',
      persistentLabel: '给高校学生使用的 AI 学习软件',
      mechanismFlow: ['学生亲自讲清', '证据审核', '改变下一步'],
    },
  },
  {
    id: 'v18-02-profile-dialogue',
    sequence: 2,
    title: '画像不是填表生成的，是从真实对话里长出来的',
    uniquePoint: '个性化从真实对话开始，初始画像只是一组待验证假设。',
    subtitle: '学生每答一次，AI 的下一问就必须改变',
    narration: '第一次进入仓库，系统不让小林填写一张固定问卷，而是一次只问一个必要问题：想学什么、现在会什么、怎样更容易理解、最常卡在哪里。每一问都根据上一回答继续。对话结束后形成的只是初始画像，后续表现还会继续修正它，并改变提问和资源。',
    media: {
      mode: 'continuous-product-video',
      master: 'M01',
      status: V18_MEDIA_STATUS.MISSING,
      candidates: [],
      plannedFile: 'assets/videos/M01-initial-profile-dialogue.mp4',
      missing: ['出现第一问', '学生完成回答', '下一问随回答改变', '提示画像已更新', '进入认知洞察'],
      note: '待补录第一问、学生回答、变化后的下一问、画像更新提示和认知洞察入口。',
    },
    beats: [
      { time: '0-3', visual: '初始画像面板与第一问', text: '主标题' },
      { time: '3-20', visual: '至少两轮连续问答', text: '上一回答 → 改变下一问' },
      { time: '20-27', visual: '初始画像已更新', text: '待验证的初始假设' },
      { time: '27-31', visual: '进入认知洞察', text: '查看画像变化' },
    ],
    visual: {
      layout: 'adaptive-dialogue',
      focus: 'question-changes-after-answer',
      profileDimensions: ['目标', '基础', '理解方式', '常见卡点'],
      completionState: '初始画像已更新',
    },
  },
  {
    id: 'v18-03-profile-insights',
    sequence: 3,
    title: '画像里的每个判断，都能回到学生原话',
    uniquePoint: '学生能看见并纠正 AI 对自己的理解。',
    subtitle: '依据强弱可见｜前后变化可见｜学生可以纠正',
    narration: '在认知洞察中，小林能看到“偏好分步可视化”来自哪句原话、依据强弱和前后变化，也可以纠正。画像不是后台标签，而是一份双方都能检查和修正的教学假设。系统初步认识了小林，接下来放入真实课程资料。',
    media: {
      mode: 'product-video+freeze-highlights',
      master: 'M01',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: ['assets/videos/scene-24-profile-insights.mp4'],
      missing: [],
      note: '候选素材需核验是否同时包含原话来源、依据强弱、变化记录和纠正入口。',
    },
    beats: [
      { time: '0-3', visual: '展开具体画像判断', text: '主标题' },
      { time: '3-8', visual: '返回学生原始回答', text: '判断有来源' },
      { time: '8-13', visual: '置信度和变化记录', text: '依据强弱 → 前后变化' },
      { time: '13-18', visual: '纠正入口', text: '学生可以纠正' },
    ],
    visual: {
      layout: 'insight-evidence-zoom',
      focusClaim: '偏好分步可视化',
      callouts: ['原话来源', '依据强弱', '前后变化', '纠正入口'],
      backgroundTreatment: '局部停帧高亮',
    },
  },
  {
    id: 'v18-04-import',
    sequence: 4,
    title: '一份 PDF，直接变成可以继续学习的知识节点',
    uniquePoint: '资料不是换一个地方保存，而是被转换成可以学习的知识点。',
    subtitle: '不只是保存：来源 → 知识点 → 关系 → 卡片',
    narration: '小林导入讲解库存并发的课程资料。系统保留来源，把文件拆成可以提问、关联和审核的知识点。解析完成后，新的节点和关系出现在仪表盘中：这份 PDF 不再只是收藏，而是进入了学习环境。',
    media: {
      mode: 'continuous-product-video+progress-labels',
      master: 'M02',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: ['assets/videos/scene-19-course-import.mp4'],
      missing: [],
      note: '必须与第 05 页使用同一仓库、同一份 PDF，并证明导入前后状态变化。',
    },
    beats: [
      { time: '0-3', visual: '选择课程 PDF', text: '主标题' },
      { time: '3-8', visual: '文件、主题和来源进入系统', text: '来源已保留' },
      { time: '8-14', visual: '解析进度推进', text: '知识点 → 关系 → 卡片' },
      { time: '14-18', visual: '返回 Dashboard', text: 'PDF → 知识节点' },
    ],
    visual: {
      layout: 'import-transformation',
      focus: 'inventory-concurrency-pdf',
      pipeline: ['来源', '知识点', '关系', '卡片'],
      beforeAfter: ['导入前无本次节点', '导入后新增节点与关系'],
    },
  },
  {
    id: 'v18-05-dashboard-cards',
    sequence: 5,
    title: '看过、正在理解、已经掌握，三种状态不能混在一起',
    uniquePoint: '学生能同时看见课程知识结构和自己的掌握状态。',
    subtitle: '文献卡＝资料来源｜灵感卡＝尚未掌握｜永久卡＝已经掌握',
    narration: '仪表盘上的节点是知识点，连线是知识关系，中央图谱展示课程结构。AXIOM 借鉴卢曼卡片盒的长期连接思想：粉色文献卡保存来源，青色灵感卡表示尚未掌握，紫色永久卡表示已经掌握。看过和学会，不能放进同一个盒子里。',
    media: {
      mode: 'product-video+zoom+card-animation',
      master: 'M02',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: ['assets/videos/scene-25-dashboard-after-import.mp4'],
      missing: [],
      note: '需核验左侧数量、中央图谱和三类卡片来自同一仓库状态。',
    },
    beats: [
      { time: '0-5', visual: 'Dashboard 与新增节点', text: '主标题' },
      { time: '5-10', visual: '数量与中央图谱对应', text: '同一仓库状态' },
      { time: '10-22', visual: '三类卡片依次放大', text: '来源 → 尚未掌握 → 已经掌握' },
      { time: '22-26', visual: '三个卡片盒同屏', text: '卢曼思想借鉴｜AXIOM 状态设计' },
      { time: '26-31', visual: '停在青色灵感卡', text: '看过 ≠ 学会' },
    ],
    visual: {
      layout: 'dashboard-card-boxes',
      focusNode: '并发库存超卖',
      cardBoxes: [
        { type: 'literature', color: 'pink', meaning: '资料来源' },
        { type: 'fleeting', color: 'cyan', meaning: '尚未掌握' },
        { type: 'permanent', color: 'purple', meaning: '已经掌握' },
      ],
      sourceLabel: '卢曼思想借鉴｜学习状态由 AXIOM 设计',
    },
  },
  {
    id: 'v18-06-open-fleeting',
    sequence: 6,
    title: '图谱不只是用来看的，点开哪里不会，就从哪里继续学',
    uniquePoint: '从图谱进入工作台，学习的仍是同一个知识点。',
    subtitle: '青色灵感卡 → 同一知识节点 → 知识打磨工作台',
    narration: '小林从图谱点击青色“并发库存超卖”灵感卡，工作台打开同一节点，并带入资料和卡片。Agent A 先让小林自己讲。',
    media: {
      mode: 'continuous-navigation-video',
      master: 'M03',
      status: V18_MEDIA_STATUS.REJECTED,
      candidates: ['assets/videos/scene-04-course-to-workbench.mp4'],
      missing: ['Dashboard 青色灵感卡 → 同名工作台节点的连续实录（若候选不符合）'],
      note: '候选旧用途是“课程路径进入工作台”；起点和终点不符合时必须补录。',
    },
    beats: [
      { time: '0-2', visual: '点击青色节点', text: '主标题' },
      { time: '2-5', visual: '持续追踪同一节点名称', text: '青色灵感卡 → 同一节点' },
      { time: '5-8', visual: '工作台显示卡片与来源', text: '知识打磨工作台' },
    ],
    visual: {
      layout: 'node-continuity-trace',
      sourceSurface: 'Dashboard 图谱',
      targetSurface: '知识打磨工作台',
      continuityKeys: ['并发库存超卖', '资料来源', '已有卡片内容'],
      forbiddenTransitions: ['重新选课', '重新搜索', '黑场'],
    },
  },
  {
    id: 'v18-07-agent-dialogue',
    sequence: 7,
    title: 'AI 不替学生回答，学生必须自己讲明白',
    uniquePoint: '学生负责产生理解，AI 负责追问和保留证据。',
    subtitle: 'Agent A 追问 → 学生费曼输出 → Agent B 保留证据',
    narration: 'Agent A 让小林预测两个请求会怎样读写库存，再追问为什么、何时会失效。小林用自己的话解释，并在新场景中举例，这就是费曼输出。Agent B 不替他回答，只保存原话、更新画像和灵感卡。系统还找回一张过去掌握的相似永久卡帮助类比；相似只负责搭桥，不能替当前回答通过审核。',
    media: {
      mode: 'continuous-dialogue-video',
      master: 'M03',
      status: V18_MEDIA_STATUS.FRAGMENTED,
      candidates: [
        'assets/videos/scene-06-dialogue-to-card.mp4',
        'assets/videos/scene-05-recall-prior-knowledge.mp4',
      ],
      missing: ['状态连续的 Agent A → 学生 → Agent B → 旧卡召回母带'],
      note: '现有素材只有分段候选；不能让旧卡像另一个案例突然插入。',
    },
    beats: [
      { time: '0-11', visual: 'Agent A 连续追问', text: 'Agent A：追问' },
      { time: '11-23', visual: '学生完整解释和举例', text: '学生：费曼输出' },
      { time: '23-31', visual: 'Agent B 写回状态', text: '保留原话 → 更新画像 → 写回灵感卡' },
      { time: '31-38', visual: '打开旧永久卡正文与来源', text: '旧知只负责搭桥' },
      { time: '38-42', visual: '返回当前青色卡', text: '当前掌握仍要重新验证' },
    ],
    visual: {
      layout: 'three-party-evidence-chain',
      roles: {
        agentA: '苏格拉底式追问',
        student: '用自己的话完成费曼输出',
        agentB: '保留原话、更新画像与灵感卡',
      },
      retrievalBadge: '语义 / 向量检索',
      retrievalBoundary: '相似旧知只负责搭桥，不能替当前审核',
    },
  },
  {
    id: 'v18-08-review-rule',
    sequence: 8,
    title: 'AI 写得再漂亮，也不能直接算学生掌握',
    uniquePoint: 'AI 可以整理表达，但无权直接宣布学生已经掌握。',
    subtitle: '讲清机制｜处理边界｜新情境能用｜依据可追溯',
    narration: '永久卡代表已经掌握，因此 Agent B 只能提交审核，不能直接把卡片变紫。审核检查学生能否自己讲清机制、处理边界并应用到新情境；判断必须回到原话和依据。',
    media: {
      mode: 'product-video-freeze+rule-animation',
      master: 'M03',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: ['assets/videos/scene-07-review-rejects-card.mp4'],
      missing: [],
      note: '需核验青色卡、学生原话、审核入口与规则属于同一知识节点。',
    },
    beats: [
      { time: '0-3', visual: '青色卡与审核入口同屏', text: '主标题' },
      { time: '3-11', visual: '四项标准依次高亮', text: '机制 → 边界 → 新情境 → 可追溯' },
      { time: '11-14', visual: '高亮学生原话与来源', text: '判断必须回到依据' },
      { time: '14-17', visual: '点击提交审核', text: '第一次审核' },
    ],
    visual: {
      layout: 'review-panel-freeze',
      cardState: 'cyan-fleeting',
      reviewCriteria: ['讲清机制', '处理边界', '新情境能用', '依据可追溯'],
      authorityBoundary: 'Agent B 只能提交，不能直接改成永久卡',
    },
  },
  {
    id: 'v18-09-review-loop',
    sequence: 9,
    title: '没讲清，就不能算掌握',
    uniquePoint: '没讲清就继续学；达到标准后，灵感卡才升级为永久卡。',
    subtitle: '拒绝升级 → 只追问缺口 → 新情境作答 → 通过审核',
    narration: '第一次审核发现小林讲了超卖机制，却没有说明它成立的前提，因此卡片仍是青色灵感卡。审核结果立即返回对话，Agent A 只追问这个缺口；小林补上反例，并把同一机制应用到新的优惠券场景。第二次审核能回到他的原话、标准和新作答，因此通过，卡片由青变紫，成为永久卡，代表这项知识已经掌握。路径随即跳过“并发库存超卖”，把不同的“锁方案选择与失效边界”标成下一节点。',
    media: {
      mode: 'continuous-review-loop-video',
      master: 'M03',
      status: V18_MEDIA_STATUS.FRAGMENTED,
      candidates: [
        'assets/videos/scene-07-review-rejects-card.mp4',
        'assets/videos/scene-09-transfer-and-pass.mp4',
        'assets/videos/scene-10-evidence-changes-next-step.mp4',
      ],
      missing: ['知识节点、学生原话与仓库状态连续的完整审核母带（若分段无法验收）'],
      note: '三个候选必须证明是同一节点的失败、打磨、通过与路径变化。',
    },
    beats: [
      { time: '0-8', visual: '第一次失败且保持青色', text: '成立前提没讲清 → 拒绝升级' },
      { time: '8-16', visual: '失败结果返回对话', text: '只追问这个缺口' },
      { time: '16-28', visual: '反例与优惠券新情境', text: '换个场景，仍要独立讲清' },
      { time: '28-42', visual: '第二次审核通过并青变紫', text: '永久卡＝已经掌握' },
      { time: '42-46', visual: '路径跳过当前节点', text: '证据改变下一步' },
    ],
    visual: {
      layout: 'review-state-transition',
      failureReason: '超卖机制的成立前提没有讲清',
      transferScenario: '最后一张优惠券',
      cardTransition: ['cyan-fleeting', 'purple-permanent'],
      nextGap: '锁方案选择与失效边界',
    },
  },
  {
    id: 'v18-10-resource-request',
    sequence: 10,
    title: '学生知道自己缺什么，直接点名要资源',
    uniquePoint: '学生知道自己需要什么时，可以主动选择资源形式。',
    subtitle: '“锁方案何时失效”对比动画 → 生成 → 打开真实预览',
    narration: '刚掌握的“并发库存超卖”被路径跳过，“锁方案选择与失效边界”成为新缺口。小林主动请求一段“不同锁方案何时失效”的对比动画；系统只生成他选择的资源，并打开真实预览。',
    media: {
      mode: 'continuous-resource-video',
      master: 'M04',
      status: V18_MEDIA_STATUS.REJECTED,
      candidates: ['assets/videos/scene-08-generate-only-video.mp4'],
      missing: ['上下文明确为“锁方案选择与失效边界”的主动生成实录（若候选不符合）'],
      note: '旧案例中的孤立生成任务不能代替当前新缺口的证据。',
    },
    beats: [
      { time: '0-3', visual: '新缺口被高亮', text: '主标题' },
      { time: '3-7', visual: '学生选择视频或对比动画', text: '学生主动选择形式' },
      { time: '7-12', visual: '单个生成任务完成', text: '对比动画 → 生成' },
      { time: '12-17', visual: '打开真实预览', text: '打开真实预览' },
    ],
    visual: {
      layout: 'active-resource-request',
      currentGap: '锁方案选择与失效边界',
      requestedResource: '不同锁方案何时失效的对比动画',
      userControl: '学生主动选择形式',
      deliveryProof: '生成完成并打开真实预览',
    },
  },
  {
    id: 'v18-11-resource-recommendation',
    sequence: 11,
    title: '学生不知道该补什么时，系统推荐资源必须说明理由',
    uniquePoint: '学生不知道该补什么时，系统提出有依据、可拒绝的建议。',
    subtitle: '知识缺口决定补什么｜学习偏好决定怎么补｜学生确认后才生成',
    narration: '有时学生并不知道该补什么。系统结合图谱缺口、学习画像和当前卡点，建议一张流程图和一组边界题，并说明来源、理由、证据强度与预期结果。小林可以接受或忽略，确认后才生成。',
    media: {
      mode: 'recommendation-card-video+field-highlights',
      master: 'M04',
      status: V18_MEDIA_STATUS.MISSING,
      candidates: [],
      plannedFile: 'assets/videos/M04-system-resource-recommendation.mp4',
      missing: ['显示当前知识缺口', '引用画像偏好与本轮卡点', '给出推荐理由和证据强度', '同时提供接受与忽略', '确认后才生成'],
      note: '待补录缺口、画像偏好、卡点、证据强度、预期结果及接受/忽略入口。',
    },
    beats: [
      { time: '0-3', visual: '真实建议卡出现', text: '主标题' },
      { time: '3-9', visual: '高亮缺口与本轮对话', text: '缺口决定补什么' },
      { time: '9-15', visual: '高亮偏好、理由和强度', text: '学习偏好决定怎么补' },
      { time: '15-18', visual: '接受与忽略同屏', text: '学生可接受或忽略' },
      { time: '18-22', visual: '确认后开始生成', text: '确认后才生成' },
    ],
    visual: {
      layout: 'recommendation-evidence-card',
      recommendation: ['流程图', '边界题'],
      fields: ['来源', '理由', '证据强度', '预期结果'],
      controls: ['接受', '忽略'],
      executionBoundary: '学生确认后才生成',
    },
  },
  {
    id: 'v18-12-resource-types',
    sequence: 12,
    title: '六类资源，不是同一回答换六个文件后缀',
    uniquePoint: '六类资源不是六个文件后缀，而是六种学习动作。',
    subtitle: '文档＝讲解｜导图＝梳理｜题目＝验证｜代码＝实操｜图示＝说明｜视频＝演示',
    narration: '同一个缺口可以用文档讲解、导图梳理、题目验证、代码实操、图示说明或视频演示。六类内容分别生成和预览；关键是能否补上缺口。',
    media: {
      mode: 'resource-panel-video+preview-grid',
      master: 'M04',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: ['assets/videos/scene-20-six-resources.mp4'],
      missing: [],
      note: '需核验六类均为真实不同内容，并至少完整打开两类代表结果。',
    },
    beats: [
      { time: '0-3', visual: '六类真实缩略预览', text: '主标题' },
      { time: '3-9', visual: '六种预览产生动态反馈', text: '六种资源，六种学习动作' },
      { time: '9-14', visual: '打开边界题', text: '题目＝验证' },
      { time: '14-18', visual: '打开动画或视频', text: '视频＝演示' },
      { time: '18-20', visual: '返回同一知识节点', text: '关键是补上缺口' },
    ],
    visual: {
      layout: 'six-resource-grid',
      resourcePurposes: {
        document: '讲解',
        mindmap: '梳理',
        quiz: '验证',
        code: '实操',
        diagram: '说明',
        video: '演示',
      },
      fullPreviewTargets: ['边界题', '对比动画或视频'],
    },
  },
  {
    id: 'v18-13-graph-source',
    sequence: 13,
    title: '图谱不只显示连线，当前知识能追到原始资料和对话',
    uniquePoint: '同一网络可以回答知识属于哪里、怎样连接、来自哪里。',
    subtitle: '看领域｜看连接｜看证据从哪里来',
    narration: '最后回到同一张知识图谱。星团模式看课程领域，关系模式看知识连接，来源模式回到原始资料和对话。视角在变，节点和证据没有变。',
    media: {
      mode: 'continuous-graph-mode-video',
      master: 'M05',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: ['assets/videos/scene-21-galaxy-views.mp4'],
      missing: [],
      segment: 'front-half',
      note: '需核验三种模式真实存在，且来源模式可以打开资料或对话。',
    },
    beats: [
      { time: '0-3', visual: '聚焦同一知识节点', text: '主标题' },
      { time: '3-7', visual: '切换星团模式', text: '看课程领域' },
      { time: '7-11', visual: '切换关系模式', text: '看知识连接' },
      { time: '11-16', visual: '切换来源模式并打开来源', text: '看证据从哪里来' },
      { time: '16-17', visual: '保持同一节点并移向下一组模式', text: '结果句退出' },
    ],
    visual: {
      layout: 'graph-source-modes',
      focusNode: '并发库存超卖',
      modes: [
        { id: 'cluster', label: '星团模式', question: '看课程领域' },
        { id: 'relation', label: '关系模式', question: '看知识连接' },
        { id: 'source', label: '来源模式', question: '看证据从哪里来' },
      ],
      invariant: '节点身份与证据内容不变',
    },
  },
  {
    id: 'v18-14-graph-mastery-path',
    sequence: 14,
    title: '刚掌握的，从当前路径跳过；下一处缺口，成为新的学习节点',
    uniquePoint: '同一网络可以回答哪些尚未掌握、哪些已经掌握、下一步学什么。',
    subtitle: '看知识阶段｜看掌握状态｜看下一学习节点',
    narration: '卡片模式看知识处于哪个阶段，掌握模式区分尚未掌握与已经掌握，路径模式呈现下一步。刚通过审核的永久卡被跳过，“锁方案选择与失效边界”成为下一节点。图谱是同一份学习证据的不同读法。',
    media: {
      mode: 'continuous-graph-mode-video',
      master: 'M05',
      status: V18_MEDIA_STATUS.UNVERIFIED,
      candidates: [
        'assets/videos/scene-21-galaxy-views.mp4',
        'assets/videos/scene-10-evidence-changes-next-step.mp4',
      ],
      missing: ['审核完成后同一仓库状态的三模式连续实录（若候选无法核验）'],
      segment: 'back-half+path-evidence',
      note: '不得用普通换色或学习前的旧状态模拟掌握与路径变化。',
    },
    beats: [
      { time: '0-4', visual: '切换卡片模式', text: '看知识阶段' },
      { time: '4-8', visual: '切换掌握模式', text: '看掌握状态' },
      { time: '8-14', visual: '切换路径模式并跳过当前节点', text: '主标题' },
      { time: '14-17', visual: '停在新学习节点', text: '图谱只呈现学习结果' },
    ],
    visual: {
      layout: 'graph-mastery-path-modes',
      modes: [
        { id: 'card', label: '卡片模式', question: '看知识阶段' },
        { id: 'mastery', label: '掌握模式', question: '看掌握状态' },
        { id: 'path', label: '路径模式', question: '看下一学习节点' },
      ],
      masteredNode: '并发库存超卖',
      nextGap: '锁方案选择与失效边界',
      truthNote: '图谱呈现学习结果，不凭视觉位置判断掌握',
    },
  },
  {
    id: 'v18-15-closing',
    sequence: 15,
    eyebrow: 'AXIOM Space｜给高校学生使用的 AI 掌握学习系统',
    title: '不看 AI 生成了多少，只看学生是否真的学会',
    uniquePoint: 'AXIOM 的长期价值是让真实掌握继续改变以后的学习。',
    subtitle: '学生必须输出 → 掌握必须有证据 → 证据必须改变下一步',
    finalVision: '让高质量、个性化、可持续的学习反馈更容易获得',
    narration: 'AXIOM 不以生成更多内容为终点。它让学生亲自输出，让 AI 的判断受证据约束，再让证据改变画像、卡片、资源和路径。学生知道哪里尚未掌握，旧理解也能参与新问题。我们的愿景，是让高质量、个性化、可持续的学习反馈更容易获得。',
    media: {
      mode: 'evidence-montage+static-final-card',
      master: 'M06',
      status: V18_MEDIA_STATUS.ASSEMBLY_PENDING,
      candidates: [
        'assets/videos/scene-24-profile-insights.mp4',
        'assets/videos/scene-07-review-rejects-card.mp4',
        'assets/videos/scene-09-transfer-and-pass.mp4',
        'assets/videos/scene-10-evidence-changes-next-step.mp4',
      ],
      missing: ['真实旧永久卡召回镜头', '最终定格与转场动画'],
      note: '不得为 10.5—12 秒的旧知召回虚构未映射素材。',
    },
    beats: [
      { time: '0-3', visual: '画像判断返回原话', text: '判断有依据' },
      { time: '3-6', visual: '审核失败且保持青色', text: '没讲清，就继续学' },
      { time: '6-10.5', visual: '审核通过、青变紫并改变路径', text: '掌握必须有证据 → 证据改变下一步' },
      { time: '10.5-18', visual: '旧知召回与三条结论', text: '旧理解参与新问题 → 输出 → 证据 → 下一步' },
      { time: '18-27', visual: '唯一静态最终定格', text: '产品定位＋主标题＋最终愿景' },
    ],
    visual: {
      layout: 'closing-evidence-montage',
      montageOrder: ['画像回到原话', '审核失败', '青变紫', '路径改变', '旧知召回'],
      closingStatements: ['学生必须输出', '掌握必须有证据', '证据必须改变下一步'],
      finalCard: {
        title: '不看 AI 生成了多少，只看学生是否真的学会',
        vision: '让高质量、个性化、可持续的学习反馈更容易获得',
      },
    },
  },
]
