import { ORACLE_CHAT_PROMPT } from './tasks/oracle-chat';
import {
  LEARNING_BATCH_CONCEPTS_PROMPT,
  LEARNING_PATH_PLANNER_PROMPT,
  LEARNING_STEP_EVALUATION_PROMPT,
} from './tasks/learning-path';
import {
  DOCUMENT_CHUNK_EXTRACTION_PROMPT,
  DOCUMENT_IMPORT_PATH_PROMPT,
  DOCUMENT_PARSE_PROMPT,
} from './tasks/document-import';
import {
  GRAPH_LINK_SUGGESTION_PROMPT,
  GRAPH_RELATION_ANALYSIS_PROMPT,
} from './tasks/graph-relation';
import { BACKGROUND_ANALYSIS_PROMPT } from './tasks/background-analysis';
import {
  BACKGROUND_REVIEW_PROMPT,
  INTENT_ROUTER_PROMPT,
  JSON_REPAIR_PROMPT,
  MEMORY_FLUSH_PROMPT,
  MEMORY_SUMMARY_PROMPT,
  SESSION_SUMMARY_PROMPT,
  SKILL_DUPLICATE_PROMPT,
  WEB_SEARCH_ANSWER_PROMPT,
} from './tasks/utility';
import { RESOURCE_GENERATION_PROMPTS } from './tasks/resource-generation';
import {
  ORCHESTRATION_GENERATOR_PROMPT,
  ORCHESTRATION_PLANNER_PROMPT,
} from './tasks/orchestration';
import { AGENT_TOOL_PROMPTS } from './tasks/agent-tools';
import { SUBAGENT_PROMPTS } from './tasks/subagents';
import type { PromptContract } from './types';

export const PROMPT_REGISTRY = {
  [ORACLE_CHAT_PROMPT.id]: ORACLE_CHAT_PROMPT,
  [LEARNING_BATCH_CONCEPTS_PROMPT.id]: LEARNING_BATCH_CONCEPTS_PROMPT,
  [LEARNING_PATH_PLANNER_PROMPT.id]: LEARNING_PATH_PLANNER_PROMPT,
  [LEARNING_STEP_EVALUATION_PROMPT.id]: LEARNING_STEP_EVALUATION_PROMPT,
  [DOCUMENT_CHUNK_EXTRACTION_PROMPT.id]: DOCUMENT_CHUNK_EXTRACTION_PROMPT,
  [DOCUMENT_PARSE_PROMPT.id]: DOCUMENT_PARSE_PROMPT,
  [DOCUMENT_IMPORT_PATH_PROMPT.id]: DOCUMENT_IMPORT_PATH_PROMPT,
  [GRAPH_LINK_SUGGESTION_PROMPT.id]: GRAPH_LINK_SUGGESTION_PROMPT,
  [GRAPH_RELATION_ANALYSIS_PROMPT.id]: GRAPH_RELATION_ANALYSIS_PROMPT,
  [BACKGROUND_ANALYSIS_PROMPT.id]: BACKGROUND_ANALYSIS_PROMPT,
  [INTENT_ROUTER_PROMPT.id]: INTENT_ROUTER_PROMPT,
  [MEMORY_SUMMARY_PROMPT.id]: MEMORY_SUMMARY_PROMPT,
  [WEB_SEARCH_ANSWER_PROMPT.id]: WEB_SEARCH_ANSWER_PROMPT,
  [SKILL_DUPLICATE_PROMPT.id]: SKILL_DUPLICATE_PROMPT,
  [SESSION_SUMMARY_PROMPT.id]: SESSION_SUMMARY_PROMPT,
  [BACKGROUND_REVIEW_PROMPT.id]: BACKGROUND_REVIEW_PROMPT,
  [MEMORY_FLUSH_PROMPT.id]: MEMORY_FLUSH_PROMPT,
  [JSON_REPAIR_PROMPT.id]: JSON_REPAIR_PROMPT,
  [ORCHESTRATION_PLANNER_PROMPT.id]: ORCHESTRATION_PLANNER_PROMPT,
  [ORCHESTRATION_GENERATOR_PROMPT.id]: ORCHESTRATION_GENERATOR_PROMPT,
  ...Object.fromEntries(
    Object.values(RESOURCE_GENERATION_PROMPTS).map((prompt) => [prompt.id, prompt]),
  ),
  ...Object.fromEntries(
    Object.values(AGENT_TOOL_PROMPTS).map((prompt) => [prompt.id, prompt]),
  ),
  ...Object.fromEntries(
    Object.values(SUBAGENT_PROMPTS).map((prompt) => [prompt.id, prompt]),
  ),
} as const;

export type PromptId = keyof typeof PROMPT_REGISTRY;

export function getPrompt(id: PromptId): PromptContract<any> {
  return PROMPT_REGISTRY[id] as PromptContract<any>;
}

export function listPrompts(): PromptContract<any>[] {
  return Object.values(PROMPT_REGISTRY) as PromptContract<any>[];
}
