/**
 * HyperFrames 渲染测试脚本
 */
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { hyperframesRenderer } from '../server/core/ai/hyperframes/renderer'

async function main() {
  console.log('[Test] Starting HyperFrames render test...')

  const result = await hyperframesRenderer.render({
    scenes: [
      {
        id: 'intro',
        duration: 3,
        backgroundColor: '#1a1a2e',
        elements: [
          {
            type: 'text',
            x: 240,
            y: 200,
            content: 'AXIOM SPACE',
            fontSize: 72,
            color: '#a855f7',
            fontWeight: 'bold',
            animation: { type: 'fadeIn', duration: 1 }
          },
          {
            type: 'text',
            x: 300,
            y: 350,
            content: 'HyperFrames Video Engine',
            fontSize: 32,
            color: '#22d3ee',
            animation: { type: 'slideIn', duration: 1, delay: 0.5 }
          }
        ]
      },
      {
        id: 'content',
        duration: 4,
        backgroundColor: '#0f0f23',
        elements: [
          {
            type: 'text',
            x: 200,
            y: 150,
            content: 'AI 驱动 → 知识图谱 → 视频生成',
            fontSize: 48,
            color: '#ffffff',
            fontWeight: 'bold',
            animation: { type: 'scale', duration: 0.8 }
          },
          {
            type: 'text',
            x: 280,
            y: 300,
            content: 'Puppeteer + FFmpeg 实时渲染管线',
            fontSize: 28,
            color: '#818cf8',
            animation: { type: 'slideIn', duration: 0.8, delay: 0.3 }
          },
          {
            type: 'text',
            x: 350,
            y: 420,
            content: 'GSAP 动画 · 1920×1080 · 30fps',
            fontSize: 20,
            color: '#64748b',
            animation: { type: 'fadeIn', duration: 0.6, delay: 0.8 }
          }
        ]
      },
      {
        id: 'outro',
        duration: 3,
        backgroundColor: '#1a1a2e',
        elements: [
          {
            type: 'text',
            x: 300,
            y: 250,
            content: 'Generated by AXIOM',
            fontSize: 56,
            color: '#22c55e',
            fontWeight: 'bold',
            animation: { type: 'scale', duration: 1 }
          }
        ]
      }
    ],
    width: 1280,
    height: 720,
    fps: 24,
  }, {
    outputPath: join(tmpdir(), 'axiom-hyperframes-test.mp4'),
  })

  console.log('\n[Test] Render result:', JSON.stringify(result, null, 2))

  if (result.success) {
    console.log(`\n✅ Video generated at: ${result.outputPath}`)
    console.log(`   Duration: ${result.durationMs}ms`)
    console.log(`   Frames: ${result.framesEncoded}`)
    console.log(`   File size: ${result.fileSize} bytes`)
  } else {
    console.error(`\n❌ Render failed: ${result.error}`)
  }

  await hyperframesRenderer.close()
  process.exit(result.success ? 0 : 1)
}

main().catch(err => {
  console.error('[Test] Fatal error:', err)
  process.exit(1)
})
